# Generated by Django 5.0.2 on 2024-02-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='district_id',
            new_name='district',
        ),
    ]
